#!/bin/bash
# check-commit-attribution.sh
# Utility script to check and strip AI co-authorship attribution from commit messages.
# Supports three modes:
#   --stdin: Read message from stdin, check for attribution, exit 0 if clean, 1 if found
#   --strip: Read message from stdin, remove attribution lines, print to stdout
#   <msgfile>: Read message from file, check for attribution, exit 0 if clean, 1 if found

set -e

# Attribution patterns to detect and strip
# These match common AI tool attribution formats
ATTRIBUTION_PATTERNS=(
  "Ultraworked with"
  "Worked with"
  "Co-authored by"
  "Assisted by"
  "Generated by"
  "Powered by"
  "With help from"
)

# Tool markers to detect
TOOL_MARKERS=(
  "Sisyphus"
  "Clio"
  "Claude"
  "Copilot"
  "OpenAI"
  "Codex"
  "Gemini"
  "Cursor"
  "Anthropic"
  "oh-my-openagent"
  "oh-my-opencode"
)

mode="check"
input_file=""

# Parse arguments
if [ "$1" = "--stdin" ]; then
  mode="stdin"
elif [ "$1" = "--strip" ]; then
  mode="strip"
elif [ -n "$1" ]; then
  input_file="$1"
  mode="check"
fi

# Read input
if [ "$mode" = "stdin" ] || [ "$mode" = "strip" ]; then
  message=$(cat)
elif [ -n "$input_file" ]; then
  message=$(cat "$input_file")
else
  echo "Usage: $0 [--stdin|--strip|<msgfile>]" >&2
  exit 1
fi

# Function to check if message contains attribution
has_attribution() {
  local msg="$1"
  
  # Check for attribution patterns
  for pattern in "${ATTRIBUTION_PATTERNS[@]}"; do
    if echo "$msg" | grep -qi "$pattern"; then
      return 0  # Found attribution
    fi
  done
  
  # Check for tool markers
  for marker in "${TOOL_MARKERS[@]}"; do
    if echo "$msg" | grep -qi "$marker"; then
      return 0  # Found tool marker
    fi
  done
  
  return 1  # No attribution found
}

# Function to strip attribution
strip_attribution() {
  local msg="$1"
  
  # Remove lines containing attribution patterns or tool markers
  local result="$msg"
  
  # Remove lines with attribution patterns
  for pattern in "${ATTRIBUTION_PATTERNS[@]}"; do
    result=$(echo "$result" | grep -vi "$pattern")
  done
  
  # Remove lines with tool markers
  for marker in "${TOOL_MARKERS[@]}"; do
    result=$(echo "$result" | grep -vi "$marker")
  done
  
  # Remove trailing blank lines
  result=$(echo "$result" | sed -e :a -e '/^\s*$/d;N;ba')
  
  echo "$result"
}

# Execute based on mode
case "$mode" in
  stdin)
    if has_attribution "$message"; then
      exit 1
    else
      exit 0
    fi
    ;;
  strip)
    stripped=$(strip_attribution "$message")
    echo "$stripped"
    exit 0
    ;;
  check)
    if has_attribution "$message"; then
      exit 1
    else
      exit 0
    fi
    ;;
esac
